import pytest
import json
from unittest.mock import AsyncMock, MagicMock
from agents.quality_control.validation import ValidationAgent
from agents.quality_control.schemas import AgentResponse
from app.services.llm_interface import LLMServiceInterface
from app.models.request_models import Message


@pytest.mark.asyncio
async def test_validation_agent_flow():
    mock_llm = MagicMock(spec=LLMServiceInterface)

    # First call: LLM decides to use the python scanner tool
    first_llm_response = Message(
        role="assistant",
        content=None,
        tool_calls=[
            {
                "id": "call_111",
                "type": "function",
                "function": {
                    "name": "run_deterministic_checks",
                    "arguments": '{"draft_text": "This stock is a guaranteed return!"}',
                },
            }
        ],
    )

    # Second call: LLM processes the tool results
    intermediate_llm_response = Message(
        role="assistant", content="Processed tool results."
    )

    # Third call: LLM outputs the strict ValidationResult JSON
    fake_json_output = {
        "is_valid": False,
        "violations_found": [
            "Financial guarantee violation detected (matched pattern: \\bguaranteed returns?\\b)."
        ],
        "final_approved_text": "This stock shows strong historical performance, though all investments carry risk.\n\n---\n*Disclaimer: This report is generated by AI for informational purposes and does not constitute financial advice.*",
    }

    third_llm_response = Message(role="assistant", content=json.dumps(fake_json_output))

    mock_llm.generate_message = AsyncMock(
        side_effect=[first_llm_response, intermediate_llm_response, third_llm_response]
    )

    agent = ValidationAgent(llm_service=mock_llm)

    response = await agent.execute(
        user_query="Is this stock safe?",
        draft_report="This stock is a guaranteed return!",
    )

    # Assertions
    assert isinstance(response, AgentResponse)
    assert response.status == "success"

    data = response.data
    assert data["is_valid"] is False
    assert len(data["violations_found"]) == 1
    assert "guaranteed" in data["violations_found"][0]
    assert "Disclaimer" in data["final_approved_text"]

    # Verify LLM was called three times
    assert mock_llm.generate_message.call_count == 3
