import re
from typing import Any, ClassVar


class ReportValidator:
    """
    Deterministic layer to ensure the generated report complies with system rules
    before the LLM reviews it for relevance.
    """

    # Catch implementation details bubbling up to the user-facing report.
    LEAKAGE_PATTERNS: ClassVar[list[str]] = [
        r"Traceback \(most recent call last\)",
        r"API_KEY",
    ]

    # Strict financial compliance patterns
    GUARANTEE_PATTERNS: ClassVar[list[str]] = [
        r"\bguaranteed returns?\b",
        r"\b100% risk[- ]?free\b",
        r"\bsure thing\b",
        r"\bcannot lose\b",
        r"\bwill definitely\b",
        r"\bpromise to\b",
    ]

    DISCLAIMER = "\n\n---\n*Disclaimer: This report is generated by AI for informational purposes and does not constitute financial advice.*"

    @classmethod
    def run_checks(cls, draft_text: str) -> dict[str, Any]:
        violations = []
        is_critical_failure = False

        # 1. Check for system leakage
        for pattern in cls.LEAKAGE_PATTERNS:
            if re.search(pattern, draft_text, re.IGNORECASE):
                violations.append(
                    f"System error leakage detected (matched pattern: {pattern})."
                )
                is_critical_failure = True

        # 2. Check for financial guarantees
        for pattern in cls.GUARANTEE_PATTERNS:
            if re.search(pattern, draft_text, re.IGNORECASE):
                violations.append(
                    f"Financial guarantee violation detected (matched pattern: {pattern})."
                )
                is_critical_failure = True

        # 3. Append disclaimer if not present
        final_text = draft_text
        if "Disclaimer: This report is generated by AI" not in final_text:
            final_text += cls.DISCLAIMER

        return {
            "has_violations": len(violations) > 0,
            "is_critical_failure": is_critical_failure,
            "violations": violations,
            "processed_text": final_text,
        }
