from __future__ import annotations

from typing import Any
import json

from app.core.contracts.graph_node import finalize_node_output
from app.core.graph.router_policy import decide_next_action


async def router_node(state: dict[str, Any]) -> dict[str, Any]:
    next_iteration = int(state.get("iteration_count", 0)) + 1
    decision = decide_next_action(state)
    terminal_output: Any | None = None
    if decision.startswith("terminate_") and not state.get("final_output"):
        terminal_status = (
            "insufficient_data"
            if decision == "terminate_insufficient_data"
            else "failure"
        )
        if decision == "terminate_success":
            terminal_status = "success"
        if decision == "terminate_awaiting_input":
            terminal_status = "awaiting_user_input"
            prompt_text = (
                state.get("plan", {}).get("assistant_response")
                if isinstance(state.get("plan"), dict)
                else None
            )
            prompt_text_final = (
                prompt_text
                if isinstance(prompt_text, str) and prompt_text.strip()
                else "Please provide clarification or approve the proposed plan."
            )
            terminal_output = {
                "status": terminal_status,
                "decision": "awaiting_input",
                "confidence_score": float(state.get("confidence_score", 0.0)),
                "final_confidence": float(
                    state.get("final_confidence", state.get("confidence_score", 0.0))
                ),
                "key_drivers": [],
                "risks": [],
                "data_used": state.get("data_status", {}),
                "insufficiency_markers": [],
                "reasoning": prompt_text_final,
                "next_action": "await_user_input",
            }
        else:
            terminal_output = {
                "status": terminal_status,
                "decision": "no_call" if terminal_status != "success" else "watchlist",
                "confidence_score": float(state.get("confidence_score", 0.0)),
                "final_confidence": float(
                    state.get("final_confidence", state.get("confidence_score", 0.0))
                ),
                "key_drivers": [],
                "risks": ["insufficient validated evidence"],
                "data_used": state.get("data_status", {}),
                "insufficiency_markers": ["INSUFFICIENT_DATA"],
                "reasoning": f"Terminated via router decision '{decision}'.",
                "next_action": "complete",
            }
    if not decision.startswith("terminate_"):
        # We don't want to clear the final_output generated by other nodes if we're just routing to them.
        # But if we do need to pass final_output, we should pass the existing one unless we're terminating.
        payload = {
            "iteration_count": next_iteration,
            "router_decision": decision,
            "status": "success",
            "reasoning": f"Router selected '{decision}' on iteration {next_iteration}.",
            "confidence_score": float(state.get("confidence_score", 0.0)),
            "next_action": decision,
            "data": {"router_decision": decision},
            "errors": [],
            "history": [
                {"node": "router", "decision": decision, "iteration": next_iteration}
            ],
            "final_output": state.get("final_output"),
        }
        return finalize_node_output("router_node", payload)

    payload = {
        "iteration_count": next_iteration,
        "router_decision": decision,
        "termination_reason": decision,
        "status": "success",
        "reasoning": f"Router selected '{decision}' on iteration {next_iteration}.",
        "confidence_score": float(state.get("confidence_score", 0.0)),
        "next_action": decision,
        "data": {"router_decision": decision},
        "errors": [],
        "history": [
            {"node": "router", "decision": decision, "iteration": next_iteration}
        ],
        "final_output": (
            terminal_output
            if terminal_output is not None
            else state.get("final_output")
        ),
        "final_report": (
            json.dumps(terminal_output, ensure_ascii=True)
            if terminal_output is not None and not isinstance(terminal_output, str)
            else (
                terminal_output
                if terminal_output is not None
                else state.get("final_report")
            )
        ),
    }
    return finalize_node_output("router_node", payload)
