import asyncio
import logging
import json
import random
from typing import List, Set, AsyncGenerator, Any, Optional

from app.core.observability import observe, langfuse_context
from app.core.session_logging import SessionLogger

from app.models.request_models import Message
from app.models.response_models import StreamEvent
from app.services.llama_cpp_service import LlamaCppService
from storage.sql.client import PostgresClient
from storage.vector.client import QdrantStorage
from data.providers.yfinance import YFinanceFetcher
from data.providers.rss_news import RSSNewsFetcher

from agents.base import BaseAgent, status_queue_var
from agents.orchestration.planner import PlannerAgent
from agents.data_access.market_offline import MarketOfflineAgent
from agents.data_access.market_online import MarketOnlineAgent
from agents.retrieval.agent import RetrievalAgent
from agents.analysis.fundamental import FundamentalAnalysisAgent
from agents.analysis.sentiment import SentimentAnalysisAgent
from agents.quality_control.validation import ValidationAgent
from agents.quality_control.verification import VerificationAgent
from agents.research.web_search import WebSearchAgent
from agents.analysis.macro import MacroAnalysisAgent
from agents.analysis.technical import TechnicalAnalysisAgent
from agents.analysis.contrarian import ContrarianAgent

from common.state import ResearchState, ToolResult
from agents.orchestration.schemas import ExecutionStep

logger = logging.getLogger(__name__)


class PipelineOrchestrator:
    """
    The central intelligence that executes the DAG generated by the Planner.
    It routes tasks to specific agents, aggregates their responses,
    synthesizes them, and passes them through final validation.
    """

    def __init__(self):
        # Initialize Shared Services
        self.llm: LlamaCppService = LlamaCppService()
        self.sql_db = PostgresClient()
        self.vector_db = QdrantStorage()
        self.yf_fetcher = YFinanceFetcher()
        self.rss_fetcher = RSSNewsFetcher()

        # Initialize Agents
        self.planner = PlannerAgent(llm_service=self.llm)
        self.market_offline = MarketOfflineAgent(
            llm_service=self.llm, db_client=self.sql_db
        )
        self.market_online = MarketOnlineAgent(
            llm_service=self.llm,
            yf_fetcher=self.yf_fetcher,
            rss_fetcher=self.rss_fetcher,
            sql_db=self.sql_db,
            vector_db=self.vector_db,
        )
        self.retrieval = RetrievalAgent(
            llm_service=self.llm, qdrant_client=self.vector_db
        )
        self.fundamental = FundamentalAnalysisAgent(llm_service=self.llm)
        self.sentiment = SentimentAnalysisAgent(llm_service=self.llm)
        self.macro = MacroAnalysisAgent(llm_service=self.llm)
        self.technical = TechnicalAnalysisAgent(llm_service=self.llm)
        self.contrarian = ContrarianAgent(llm_service=self.llm)
        self.validator = ValidationAgent(llm_service=self.llm)
        self.verification_agent = VerificationAgent(llm_service=self.llm)
        self.web_search = WebSearchAgent(llm_service=self.llm)

    def _group_steps(self, steps: List[ExecutionStep]) -> List[List[ExecutionStep]]:
        """Groups steps into levels based on dependencies for parallel execution."""
        levels = []
        executed_step_ids: Set[int] = set()
        remaining_steps = list(steps)

        while remaining_steps:
            current_level = []
            for step in remaining_steps[:]:
                if all(dep in executed_step_ids for dep in step.dependencies):
                    current_level.append(step)
                    remaining_steps.remove(step)

            if not current_level:
                logger.error(
                    "Detected circular dependency or missing dependency in execution plan."
                )
                break

            levels.append(current_level)
            for step in current_level:
                executed_step_ids.add(step.step_number)

        return levels

    async def _execute_step(
        self,
        step: ExecutionStep,
        user_query: str,
        state: ResearchState,
        status_queue: asyncio.Queue,
        session_logger: SessionLogger,
    ):
        """Executes a single agent step and updates the shared ResearchState."""
        agent_name = (
            step.target_agent.value
            if hasattr(step.target_agent, "value")
            else str(step.target_agent)
        )
        try:
            logger.info(f"Executing Step {step.step_number}: {agent_name}")
            status_ev = StreamEvent(
                event="status",
                data={"message": f"Step {step.step_number}: {agent_name} running..."},
            )
            await status_queue.put(status_ev)

            langfuse_context.update_current_trace(
                metadata={
                    f"step_{step.step_number}_status": "started",
                    f"step_{step.step_number}_agent": agent_name,
                }
            )

            # Aggregate context from dependent steps
            context_from_prev = "\n".join(
                [
                    f"Step {s}: {state.agent_outputs[str(s)]}"
                    for s in step.dependencies
                    if str(s) in state.agent_outputs
                ]
            )

            agent_query = f"Original Query: '{user_query}'\nAction required: {step.action}\nParameters: {step.parameters}"
            if context_from_prev:
                agent_query += f"\n\nContext from previous steps:\n{context_from_prev}"

            session_logger.log_step(
                f"DISPATCH_{agent_name.upper()}",
                f"Agent {agent_name} dispatched for step {step.step_number}.",
                parameters={
                    "step_number": step.step_number,
                    "action": step.action,
                    "parameters": step.parameters,
                    "dependencies": step.dependencies,
                    "agent_query": agent_query,
                },
            )

            # Route execution to the designated agent
            result = None
            target_agent: Optional[Any] = None
            if agent_name == "market_offline":
                target_agent = self.market_offline
            elif agent_name == "market_online":
                target_agent = self.market_online
            elif agent_name == "web_search":
                target_agent = self.web_search
            elif agent_name == "retrieval":
                target_agent = self.retrieval
            elif agent_name == "fundamental_analysis":
                target_agent = self.fundamental
            elif agent_name == "sentiment_analysis":
                target_agent = self.sentiment
            elif agent_name == "macro_analysis":
                target_agent = self.macro
            elif agent_name == "technical_analysis":
                target_agent = self.technical
            elif agent_name == "contrarian_analysis":
                target_agent = self.contrarian

            if target_agent:
                result = await target_agent.execute(agent_query, step_number=step.step_number)
            elif agent_name == "validation":
                return
            else:
                logger.warning(
                    f"Agent {agent_name} not recognized. Skipping step {step.step_number}."
                )
                await status_queue.put(
                    StreamEvent(
                        event="status",
                        data={
                            "message": f"Step {step.step_number}: Agent {agent_name} not recognized."
                        },
                    )
                )
                return

            if result and result.status == "success":
                response_content = ""
                if isinstance(result.data, dict) and "response" in result.data:
                    response_content = result.data["response"]
                elif isinstance(result.data, dict):
                    response_content = json.dumps(result.data)
                else:
                    response_content = str(result.data)

                state.agent_outputs[str(step.step_number)] = response_content

                tool_result = ToolResult(
                    tool_name=f"agent_{agent_name}",
                    input_parameters=step.parameters,
                    output_data=result.data,
                )
                tool_result.auto_extract_metrics()
                state.tool_registry.append(tool_result)

                session_logger.log_step(
                    f"AGENT_SUCCESS_{agent_name.upper()}",
                    f"Agent {agent_name} successfully processed step {step.step_number}.",
                    data=result.data,
                )
                await status_queue.put(
                    StreamEvent(
                        event="status",
                        data={"message": f"Step {step.step_number}: {agent_name} completed."},
                    )
                )
            elif result:
                logger.error(
                    f"Step {step.step_number} failed with errors: {result.errors}"
                )
                session_logger.log_step(
                    f"AGENT_FAILURE_{agent_name.upper()}",
                    f"Agent {agent_name} failed step {step.step_number}.",
                    data={"errors": result.errors},
                )
                state.agent_outputs[str(step.step_number)] = f"Error: {result.errors}"
                state.verification_errors.append(
                    f"Step {step.step_number} ({agent_name}) failed: {result.errors}"
                )
                await status_queue.put(
                    StreamEvent(
                        event="status",
                        data={"message": f"Step {step.step_number}: {agent_name} failed."},
                    )
                )

            langfuse_context.update_current_trace(
                metadata={
                    f"step_{step.step_number}_status": "completed",
                    f"step_{step.step_number}_response_len": len(
                        str(state.agent_outputs.get(str(step.step_number), ""))
                    ),
                }
            )
        except Exception as e:
            logger.error(
                f"Step {step.step_number} raised an exception: {e}", exc_info=True
            )
            session_logger.log_step(
                f"AGENT_CRASH_{agent_name.upper()}",
                f"Agent {agent_name} crashed during step {step.step_number}.",
                data={"exception": str(e)},
            )
            state.agent_outputs[str(step.step_number)] = f"Exception: {str(e)}"
            state.verification_errors.append(
                f"Step {step.step_number} ({agent_name}) crashed: {str(e)}"
            )
            await status_queue.put(
                StreamEvent(
                    event="status",
                    data={"message": f"Step {step.step_number}: {agent_name} crashed."},
                )
            )

    async def _synthesize_report(
        self,
        user_query: str,
        state: ResearchState,
        status_queue: asyncio.Queue,
        session_logger: SessionLogger,
    ) -> AsyncGenerator[StreamEvent, None]:
        """Synthesizes the gathered data into a final report with deterministic verification."""
        if not state.agent_outputs:
            yield StreamEvent(
                event="error",
                data={"content": "I gathered data but could not formulate a conclusive answer."},
            )
            return

        synthesis_prompt = f"Synthesize the following research data to answer the user's query: '{user_query}'\n\nData Gathered:\n"
        for step_num, data in state.agent_outputs.items():
            synthesis_prompt += f"Step {step_num} Result: {data}\n"

        current_synthesis_prompt = synthesis_prompt

        for attempt in range(3):
            state.retry_count = attempt
            logger.info(f"Synthesis & Verification Attempt {attempt + 1}/3")
            await status_queue.put(
                StreamEvent(
                    event="status",
                    data={"message": f"Synthesizing report (Attempt {attempt + 1}/3)..."},
                )
            )

            session_logger.log_step(
                "SYNTHESIS_PROMPT",
                f"Sending synthesis prompt to LLM. Attempt {attempt + 1}/3.",
                data={"prompt": current_synthesis_prompt},
            )

            messages = [
                Message(
                    role="system",
                    content="You are a senior financial analyst synthesizing research from multiple agents into a final, cohesive, and professional report. CRITICAL: Use only the numbers provided in the data. Do not hallucinate or estimate. Do not use numbers found in 'PREVIOUS ATTEMPT FAILED VERIFICATION' as they are placeholders or erroneous. Pay special attention to the 'contrarian_analysis' results to provide a balanced view of risks.",
                ),
                Message(role="user", content=current_synthesis_prompt),
            ]

            draft_report_task = asyncio.create_task(
                self.llm.generate(messages=messages, model="mistral-8b")
            )
            while not draft_report_task.done():
                await asyncio.sleep(2)
                if not draft_report_task.done():
                    await status_queue.put(
                        StreamEvent(event="status", data={"message": "Finishing synthesis..."})
                    )

            draft_report = await draft_report_task
            session_logger.log_step(
                "SYNTHESIS_DRAFT", "Raw report generated by LLM.", data=draft_report
            )

            await status_queue.put(
                StreamEvent(event="status", data={"message": "Verifying numeric accuracy..."})
            )
            
            verification_agent_response = await self.verification_agent.execute(
                user_query=user_query,
                draft_report=draft_report,
                tool_registry=state.tool_registry,
            )

            session_logger.log_step(
                "NUMERIC_VERIFICATION",
                "Deterministic verification of numbers in report against tool registry.",
                data=verification_agent_response.data,
            )

            if verification_agent_response.status == "success":
                is_valid = verification_agent_response.data.get("is_valid", False)
                feedback = verification_agent_response.data.get("feedback", "")
                
                if is_valid:
                    logger.info("Numeric verification passed.")
                    await status_queue.put(
                        StreamEvent(
                            event="status",
                            data={"message": "Performing final compliance check..."},
                        )
                    )

                    validation_result = await self.validator.execute(
                        user_query=user_query, draft_report=draft_report
                    )
                    session_logger.log_step(
                        "FINAL_COMPLIANCE",
                        "Compliance/Safety check result.",
                        data=validation_result.model_dump(),
                    )

                    if validation_result.status == "success":
                        val_data = validation_result.data
                        if val_data.get("is_valid", False) or val_data.get(
                            "final_approved_text"
                        ):
                            final_text = val_data.get("final_approved_text", draft_report)
                            if final_text is None:
                                final_text = draft_report
                        else:
                            yield StreamEvent(
                                event="error",
                                data={
                                    "content": "The generated report was flagged by our compliance systems."
                                },
                            )
                            return

                        # NATURAL STREAMING for verified reports
                        # Break into smaller chunks and add a natural-feeling delay
                        
                        # Split by whitespace to stream word-by-word
                        words = final_text.split(" ")
                        for i, word in enumerate(words):
                            # Append space back to all but the last word
                            content = word + (" " if i < len(words) - 1 else "")
                            yield StreamEvent(
                                event="token",
                                data={"content": content},
                            )
                            # Natural delay between 10ms and 40ms
                            await asyncio.sleep(random.uniform(0.01, 0.04))

                        return
                    else:
                        logger.error(f"Validation agent failed: {validation_result.errors}")
                        yield StreamEvent(
                            event="error",
                            data={
                                "content": f"The validation system failed to process the report: {', '.join(validation_result.errors or [])}"
                            },
                        )
                        return
                else:
                    logger.warning(
                        f"Numeric verification failed: {feedback}"
                    )
                    current_synthesis_prompt = (
                        f"{synthesis_prompt}\n\n"
                        f"PREVIOUS ATTEMPT FAILED VERIFICATION: {feedback}\n"
                        "Please correct the inaccuracies above."
                    )
            else:
                logger.error(f"Verification agent failed: {verification_agent_response.errors}")
                yield StreamEvent(
                    event="error",
                    data={"content": "Verification system error occurred."},
                )
                return

        yield StreamEvent(
            event="error",
            data={"content": "Multiple numeric consistency checks failed."},
        )

    async def execute_query(self, user_query: str) -> AsyncGenerator[dict, None]:
        """Main entry point for handling a user query through the multi-agent system (Streaming)."""
        # Immediately yield a start event to initialize the stream and bypass buffering
        yield {"event": "status", "data": {"message": "Initializing research pipeline..."}}
        
        langfuse_context.update_current_trace(
            input=user_query,
            tags=["orchestrator", "v1", "sequential", "streaming"],
            user_id="anonymous",
            metadata={"source": "cli", "version": "v1.2"},
        )

        status_queue = asyncio.Queue()
        session_logger = SessionLogger.get_logger(user_query)

        async def run_pipeline():
            # Set the status queue in the context for all agents called in this task
            token = status_queue_var.set(status_queue)
            try:
                logger.info(f"Orchestrator received query: {user_query}")
                session_logger.log_step(
                    "RECEIVE_QUERY",
                    "New research query received by the orchestrator.",
                    parameters={"query": user_query},
                )

                query_clean = user_query.lower().strip().rstrip("?.!")
                greetings = [
                    "hello",
                    "hi",
                    "hey",
                    "who are you",
                    "what can you do",
                    "good morning",
                    "good afternoon",
                    "good evening",
                ]

                is_greeting = query_clean in greetings
                is_financial = any(
                    kw in query_clean
                    for kw in [
                        "nifty",
                        "vix",
                        "sensex",
                        "reliance",
                        "stock",
                        "price",
                        "market",
                        "finance",
                        "invest",
                        "portfolio",
                        "risk",
                        "dividend",
                    ]
                )

                if is_greeting and not is_financial:
                    logger.info("Direct conversational response triggered.")
                    session_logger.log_step(
                        "CLASSIFICATION",
                        "Query identified as a non-financial greeting.",
                    )
                    await status_queue.put(
                        StreamEvent(event="status", data={"message": "Synthesizing greeting..."})
                    )
                    messages = [
                        Message(
                            role="system",
                            content="You are a senior financial intelligence assistant. Greeting the user warmly and briefly explain how you can help them with Indian stock market research, technical analysis, and fundamental deep-dives. Keep it concise.",
                        ),
                        Message(role="user", content=user_query),
                    ]
                    
                    # TRUE STREAMING for conversational responses
                    async for token_event in self.llm.generate_stream(
                        messages=messages, model="mistral-8b"
                    ):
                        if token_event["event"] == "token":
                            await status_queue.put(
                                StreamEvent(event="token", data={"content": token_event["data"]})
                            )
                    return

                await status_queue.put(
                    StreamEvent(event="status", data={"message": "Planning research strategy..."})
                )
                plan_agent_response = await self.planner.execute(user_query)

                if plan_agent_response.status == "failure" or not plan_agent_response.data:
                    logger.error(f"Planner failed: {plan_agent_response.errors}")
                    session_logger.log_error(
                        "PLANNING_FAILED",
                        "The Planner Agent failed to generate a plan.",
                        data=plan_agent_response.errors,
                    )
                    await status_queue.put(
                        StreamEvent(
                            event="error",
                            data={
                                "content": "I apologize, but I could not formulate a plan to answer your request."
                            },
                        )
                    )
                    return

                from agents.orchestration.schemas import PlanData
                plan = PlanData(**plan_agent_response.data)
                logger.info(f"Generated Plan with {len(plan.execution_steps)} steps.")
                session_logger.log_step(
                    "PLANNING_COMPLETE",
                    "Research strategy successfully mapped.",
                    data=plan.model_dump(),
                )

                if not plan.is_financial_request or not plan.execution_steps:
                    logger.info("Planner marked request as non-financial.")
                    await status_queue.put(
                        StreamEvent(event="status", data={"message": "Synthesizing response..."})
                    )
                    messages = [
                        Message(
                            role="system",
                            content="You are a helpful financial intelligence assistant. Answer the user's general query concisely.",
                        ),
                        Message(role="user", content=user_query),
                    ]
                    
                    # TRUE STREAMING for non-financial queries
                    async for token_event in self.llm.generate_stream(
                        messages=messages, model="mistral-8b"
                    ):
                        if token_event["event"] == "token":
                            await status_queue.put(
                                StreamEvent(event="token", data={"content": token_event["data"]})
                            )
                    return

                state = ResearchState(query=user_query)

                # 3. Sequential Execution (Optimized for low-memory local LLMs)
                levels = self._group_steps(plan.execution_steps)
                for i, level_steps in enumerate(levels):
                    for step in level_steps:
                        agent_name = (
                            step.target_agent.value
                            if hasattr(step.target_agent, "value")
                            else str(step.target_agent)
                        )
                        await status_queue.put(
                            StreamEvent(
                                event="status", data={"message": f"Executing: {agent_name}..."}
                            )
                        )

                        # Run agents one by one to prevent memory overflow on local hardware
                        await self._execute_step(
                            step, user_query, state, status_queue, session_logger
                        )

                # 4. Final Synthesis & Verification
                async for event in self._synthesize_report(
                    user_query, state, status_queue, session_logger
                ):
                    await status_queue.put(event)

            except Exception as e:
                logger.error(f"Orchestrator failed: {e}", exc_info=True)
                await status_queue.put(
                    StreamEvent(
                        event="error",
                        data={"content": f"An internal system error occurred: {str(e)}"},
                    )
                )
            finally:
                status_queue_var.reset(token)
                await status_queue.put(None)

        pipeline_task = asyncio.create_task(run_pipeline())

        while True:
            event = await status_queue.get()
            if event is None:
                break
            
            # Use a more robust check than isinstance to handle potential re-imports
            if hasattr(event, "model_dump"):
                yield event.model_dump()
            elif isinstance(event, dict):
                yield event
            else:
                yield {"type": "status", "message": str(event)}

        await pipeline_task
